apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rhads-demo1 
  janus-idp.io/tekton: rhads-demo1
  backstage.io/kubernetes-id: rhads-demo1
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rhads-demo1
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml